# Development and Test environment configurations are listed here
# for convenience but generally shouldn't be used.
# 
# Replace YOUR_APP with the heroku app name and YOUR_TOKEN with the
# same token used in private_pub.yml of your rails project.

production:
  server: "http://atmagofaye.herokuapp.com/faye"
  secret_token: "9ef71bc1d80066d2912787d35696d9d3aeb3145bc417f897a8ea21cde94bba9a"
  signature_expiration: 86400 # one day
